#!/bin/sh
apt-get update
sudo apt install apache2 -y
sudo ufw allow "Apache Full"
sudo apt install mysql-server -y
sudo apt install php libapache2-mod-php php-mysql -y

sudo mysql_secure_installation
sudo nano /etc/apache2/mods-enabled/dir.conf
