#!/bin/sh
sudo apt-get update
sudo apt install apache2 -y
sudo ufw allow "Apache Full"
sudo apt install mysql-server -y
sudo apt install php libapache2-mod-php php-mysql -y

sudo mysql_secure_installation
sudo nano /etc/apache2/mods-enabled/dir.conf

# must test this half still
sudo mkdir /var/www/domainTemplate
sudo chown -R $USER:$USER /var/www/domainTemplate
sudo chmod -R 755 /var/www/domainTemplate

printf "<html> \n<head> \n<title>Welcome to Your_domain!</title> \n</head> \n<body> \n<h1>Success!  The domainTemplate server block is working!</h1> \n</body> \n</html>" >> /var/www/domainTemplate/index.html


printf "<VirtualHost *:80>
    ServerAdmin webmaster@localhost
    ServerName domainTemplate
    ServerAlias www.domainTemplate
    DocumentRoot /var/www/domainTemplate
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>" >> /etc/apache2/sites-available/domainTemplate.conf


printf "<?php \nphpinfo(); \n?>" >> /var/www/domainTemplate/info.php


# run these commands manually after renaming files and folders to commit everything to apache

#sudo a2ensite domainTemplate.conf
#sudo a2dissite 000-default.conf
#sudo apache2ctl configtest
#sudo systemctl restart apache2
